# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-adff7e5f-d982-4e93-a915-bc4f5fa6cc44";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-adff7e5f-d982-4e93-a915-bc4f5fa6cc44".device = "/dev/disk/by-uuid/adff7e5f-d982-4e93-a915-bc4f5fa6cc44";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3C0D-5E34";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-544d2698-4af2-4550-b08e-a19140cc0e4c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
